// the codes for all the errors thrown by the library
type IErrorCode =
  | 'MIXED_OR_UNSUPPORTED_DATA_TYPES'
  | 'UNSUPPORTED_DATA_TYPE'
  | 'INVALID_OR_EMPTY_ARRAY'
  | 'INVALID_OR_EMPTY_OBJECT'
  | 'UNABLE_TO_SERIALIZE_JSON'
  | 'UNABLE_TO_DESERIALIZE_JSON'
  | 'UNABLE_TO_CREATE_DEEP_CLONE'
  | 'INVALID_BATCH_SIZE'
  | 'UNABLE_TO_SLUGIFY_STRING'
  | 'INVALID_TIME_STRING'
  | 'INVALID_AUTHORIZATION_HEADER';
export const ERRORS: { [key in IErrorCode]: IErrorCode } = {
  MIXED_OR_UNSUPPORTED_DATA_TYPES: 'MIXED_OR_UNSUPPORTED_DATA_TYPES',
  UNSUPPORTED_DATA_TYPE: 'UNSUPPORTED_DATA_TYPE',
  INVALID_OR_EMPTY_ARRAY: 'INVALID_OR_EMPTY_ARRAY',
  INVALID_OR_EMPTY_OBJECT: 'INVALID_OR_EMPTY_OBJECT',
  UNABLE_TO_SERIALIZE_JSON: 'UNABLE_TO_SERIALIZE_JSON',
  UNABLE_TO_DESERIALIZE_JSON: 'UNABLE_TO_DESERIALIZE_JSON',
  UNABLE_TO_CREATE_DEEP_CLONE: 'UNABLE_TO_CREATE_DEEP_CLONE',
  INVALID_BATCH_SIZE: 'INVALID_BATCH_SIZE',
  UNABLE_TO_SLUGIFY_STRING: 'UNABLE_TO_SLUGIFY_STRING',
  INVALID_TIME_STRING: 'INVALID_TIME_STRING',
  INVALID_AUTHORIZATION_HEADER: 'INVALID_AUTHORIZATION_HEADER',
};
