import type { IJSONValue, IUUIDVersion } from './shared/types.js';
import {
  isStringValid,
  isNumberValid,
  isIntegerValid,
  isTimestampValid,
  isObjectValid,
  isArrayValid,
  isEmailValid,
  isSlugValid,
  isPasswordValid,
  isOTPSecretValid,
  isOTPTokenValid,
  isJWTValid,
  isAuthorizationHeaderValid,
  isSemverValid,
  isURLValid,
  isUUIDValid,
} from './validations/index.js';
import {
  type INumberFormatConfig,
  type IDateTemplate,
  type ITimeString,
  prettifyNumber,
  prettifyDate,
  prettifyFileSize,
  prettifyBadgeCount,
  capitalizeFirst,
  toTitleCase,
  toSlug,
  truncateText,
  maskMiddle,
  applySubstitutions,
  toMS,
  stringifyJSON,
  stringifyJSONDeterministically,
  parseJSON,
  createDeepClone,
  pruneJSON,
} from './transformers/index.js';
import {
  type ISortDirection,
  type IFilterByQueryOptions,
  generateUUID,
  generateRandomString,
  generateRandomFloat,
  generateRandomInteger,
  generateSequence,
  sortPrimitives,
  sortRecords,
  shuffleArray,
  pickProps,
  omitProps,
  filterByQuery,
  delay,
  retryAsyncFunction,
  retryExternalRequest,
  extractTokenFromAuthorizationHeader,
} from './utils/index.js';

/* ************************************************************************************************
 *                                         MODULE EXPORTS                                         *
 ************************************************************************************************ */
export {
  // shared
  type IJSONValue,
  type IUUIDVersion,

  // validations
  isStringValid,
  isNumberValid,
  isIntegerValid,
  isTimestampValid,
  isObjectValid,
  isArrayValid,
  isEmailValid,
  isSlugValid,
  isPasswordValid,
  isOTPSecretValid,
  isOTPTokenValid,
  isJWTValid,
  isAuthorizationHeaderValid,
  isSemverValid,
  isURLValid,
  isUUIDValid,

  // transformers
  type INumberFormatConfig,
  type IDateTemplate,
  type ITimeString,
  prettifyNumber,
  prettifyDate,
  prettifyFileSize,
  prettifyBadgeCount,
  capitalizeFirst,
  toTitleCase,
  toSlug,
  truncateText,
  maskMiddle,
  applySubstitutions,
  toMS,
  stringifyJSON,
  stringifyJSONDeterministically,
  parseJSON,
  createDeepClone,
  pruneJSON,

  // utils
  type ISortDirection,
  type IFilterByQueryOptions,
  generateUUID,
  generateRandomString,
  generateRandomFloat,
  generateRandomInteger,
  generateSequence,
  sortPrimitives,
  sortRecords,
  shuffleArray,
  pickProps,
  omitProps,
  filterByQuery,
  delay,
  retryAsyncFunction,
  retryExternalRequest,
  extractTokenFromAuthorizationHeader,
};
